# User config
author: "Natalie Quek"
tagline: "Designer + illustrator"
description: "Hi! I'm a designer + urbanist based in Los Angeles."
keywords: "Art, Design, Illustration, Graphic Design"
email: "nsquek14@gmail.com"
linkedin: "https://www.linkedin.com/in/natalie-quek-2549bb133/"
instagram: "https://www.instagram.com/nsquek_art"
google: "https://drive.google.com/file/d/1V9Mp0wAcYq3ODwCIk0rk-GwyQgJShznt/view?usp=sharing"
github: "https://github.com/nsquek"

# Site config
baseurl: "/portfolio"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed