# User config
author: "Natalie Quek"
tagline: "Designer + illustrator"
description: "I'm a designer, illustrator + urbanist based in Los Angeles. When I'm not at my desk you can find me cycling along the LA River, creating new recipes, and befriending the neighborhood cats. "
keywords: "Art, Design, Illustration, Graphic Design"
email: "nsquek14@gmail.com"
linkedin: "https://www.linkedin.com/in/natalie-quek-2549bb133/"
instagram: "https://www.instagram.com/nsquek_art"
google: "https://drive.google.com/file/d/1Z7KZHG3Vin996_Mkk8WrSvjSAxNhxmA5/view?usp=sharing"
github: "https://github.com/nsquek"

# Site config
baseurl: "/portfolio"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed